// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymurhbiydcdvwizaucmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltdXJoYml5ZGNkdndpemF1Y21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjQ1NDUsImV4cCI6MjA2MDQwMDU0NX0.VRwDqvw9CC2K7h4Za-DGxlGeeLRyrCMshGJoWBY257c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);